### ISSUE TITLE
执行插入操作时，字段为null引起报错

### ISSUE THREAD

**Issue by chnjing94** [yangziwen/quick-dao#12]
构造一个entity对象，其中的createTime和updateTime字段为null，执行insert操作时，框架生成了以下SQL

INSERT INTO table (order_id, unique_id, sign_str, scn, tenant_id, account_date, type, create_time, update_time) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)

然后跑出了异常，信息为PreparedStatementCallback; Column 'create_time' cannot be null

这个一个bug还是有其他正确使用方式？

**Comment by yangziwen** [comment]
你好，谢谢支持哈。

我理解，你在数据库中将createTime和updateTime字段声明成了not null并指定了默认值。然后在insert时期望java对象中为null的字段，会自动使用数据库声明的默认值。

对于这个问题，我的看法跟[stackoverflow上的这个观点](https://stackoverflow.com/questions/4508622/avoid-insert-null-values-to-database-table-via-jpa)比较一致，就是不要依赖数据库中声明的默认值，尽量在java对象中填充好所有的初始值，再执行插入操作。

否则对象插入后，还需通过额外查询，为java对象中null的字段填充上持久化的内容，不然内存中的java对象就会与数据库中存储的内容存在字段上的脱节。

同时，在数据库中声明了字段的默认值，仍然无法保证程序中一定会使用这些默认值。久而久之，可能造成字段的初始值需要两边维护。

因此quick-dao目前没有实现insertSelective的操作，插入对象时，除了主键以外的所有需要持久化的字段，都要求填充初始值。

**Comment by chnjing94** [comment]
感谢回复，

我明白这样设计的道理了，quick-dao用起来很方便，文档也很完善，点赞！
